### ISSUE TITLE
Length of ARK

### ISSUE THREAD

**Issue by RoxPoNinja** [Inist-CNRS/node-inist-ark#2]
Hi Nicolas,

Would it be possible to add an additional parameter for setting the length of an ARK (without the check character at the end)?

Thanks,
Roxana

**Comment by touv** [comment]
Now, with the version 2.2.0, you can choose the length the identifier of an ARK. And so you can generate ARK like that : 
- ark:/12345/XYZ-G1VWVKZR-0
- ark:/12345/XYZ-MNC-K
- ark:/12345/CJLJ-C
- ark:/12345/7WX0

**Comment by RoxPoNinja** [comment]
Super, merci beaucoup! :-)
